#!/usr/bin/env bash
# script that changes the IP of your home computer
sudo sed -i 's/127.0.0.1\s*localhost/127.0.0.2 localhost/' /etc/hosts
if grep -q "facebook.com" /etc/hosts; then
    sudo sed -i 's/.*facebook.com/8.8.8.8 facebook.com/' /etc/hosts
else
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
fi
